on: workflow_dispatch
name: Deploy Azure Services
jobs:
  Deploy-Azure-Services:
    runs-on: ubuntu-latest
    steps:

      # Checkout code
    - uses: actions/checkout@main

      # Log into Azure
    - uses: Azure/login@v1.4.6
      with:
        creds: ${{ secrets.AZURE_CREDENTIALS }}

      # Deploy Bicep file
    - name: Deploy Services
      uses: azure/arm-deploy@v1.0.8
      with:
        scope: 'subscription'
        region: ${{ secrets.AZURE_RESOURCEGROUP_LOCATION }}
        subscriptionId: ${{ secrets.AZURE_SUBSCRIPTION }}
        resourceGroupName: ${{ secrets.AZURE_RESOURCEGROUP_NAME }}
        template: ./IaC/main.bicep
        parameters: resourceGroupName=${{ secrets.AZURE_RESOURCEGROUP_NAME }} resourceGroupLocation=${{ secrets.AZURE_RESOURCEGROUP_LOCATION }} appServiceName=${{ secrets.AZURE_APPSERVICE_NAME }}
        failOnStdErr: false


